# ================= length of string =================
length:
	gcc astrlen.c astrlen_test.c main.c -o len

# ================= comparing strings =================
comparing:
	gcc astr_cmp.c astr_cat_test.c main.c -o cmp

# ================== comparing n strings =================
comparingn:
	gcc astrn_ncmp.c astr_ncmp_test.c main.c -o ncmp

# ================= concatenation =================
concat:
	gcc astr_cat.c astr_cat_test.c main.c -o cat

# ================= n concatenation =================
nconcat:
	gcc astrncat.c astrncat_test.c main.c -o ncat

# ================= copy string =================
copy:
	gcc astr_cpy.c astrcpy_test.c main.c -o cpy

# ================= n copy string =================
ncpy:
	gcc astr_ncpy.c astr_ncpy_test.c main.c -o ncpy

# ================= case insensitive compare =================
casecmp:
	gcc astr_casecmp.c astr_casecmp_test.c main.c -o casecmp

# ================= n case insensitive compare =================
ncasecmp:	
	gcc astr_ncasecmp.c astr_ncasecmp_test.c main.c -o ncasecmp

# ================= character search =================
chr:
	gcc astr_chr.c astr_chr_test.c main.c -o chr

# ================= n character search =================
rchr:
	gcc astr_chr.c astr_rchr.c astr_rchr_test.c main.c -o rchr
# ================= clean =================
clean:
	rm -f casecmp *.o
	rm -f ncasecmp *.o
	rm -f len *.o
	rm -f cmp *.o
	rm -f ncmp *.o
	rm -f cat *.o
	rm -f ncat *.o
	rm -f cpy *.o
	rm -f ncpy *.o
	rm -f chr *.o
	rm -f rchr *.o
